In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv(r"train1.csv")

In [5]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [6]:
pd.set_option("display.max_columns", None)

In [7]:
df.shape

(1460, 81)

# data cleaning

In [8]:
df.drop_duplicates()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [9]:
df_null_clm_per = (df.isnull().sum()/df.shape[0])*100

In [10]:
df_null_clm_per

Id                0.000000
MSSubClass        0.000000
MSZoning          0.000000
LotFrontage      17.739726
LotArea           0.000000
                   ...
MoSold            0.000000
YrSold            0.000000
SaleType          0.000000
SaleCondition     0.000000
SalePrice         0.000000
Length: 81, dtype: float64

In [11]:
df_null_clm_per[df_null_clm_per > 20]

Alley          93.767123
MasVnrType     59.726027
FireplaceQu    47.260274
PoolQC         99.520548
Fence          80.753425
MiscFeature    96.301370
dtype: float64

In [12]:
null_clm_list = df_null_clm_per[df_null_clm_per > 20].index

In [13]:
null_clm_list

Index(['Alley', 'MasVnrType', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='str')

In [14]:
df1 = df.drop(columns= null_clm_list)

In [15]:
df1.shape

(1460, 75)

In [16]:
df1

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,0,6,2008,WD,Normal,147500

In [17]:
df_num_col = df1.select_dtypes(include= ['int','float'])

In [18]:
df_obj_col = df1.select_dtypes(include= ['object'])

C:\Users\HP\AppData\Local\Temp\ipykernel_15672\330544165.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_obj_col = df1.select_dtypes(include= ['object'])

In [19]:
df_num_col

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.0,2,548,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.0,2,460,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.0,2,608,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.0,3,642,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.0,3,836,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,0,953,953,953,694,0,1647,0,0,2,1,3,1,7,1,1999.0,2,460,0,40,0,0,0,0,0,8,2007,175000
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,163,589,1542,2073,0,0,2073,1,0,2,0,3,1,7,2,1978.0,2,500,349,0,0,0,0,0,0,2,2010,210000
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,0,877,1152,1188,1152,0,2340,0,0,2,0,4,1,9,2,1941.0,1,252,0,60,0,0,0,0,2500,5,2010,266500
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,1029,0,1078,1078,0,0,1078,1,0,1,0,2,1,5,0,1950.0,1,240,366,0,112,0,0,0,0,4,2010,142125
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,290,136,1256,1256,0,0,1256,1,0,1,1,3,1,6,0,1965.0,1,276,736,68,0,0,0,0,0,6,2008,147500

In [20]:
df_num_col.shape

(1460, 38)

In [21]:
df_obj_col

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1456,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,Attchd,Unf,TA,TA,Y,WD,Normal
1457,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1458,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
1459,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal

In [22]:
df_obj_col.shape

(1460, 37)

In [23]:
df_num_col.isnull().sum()

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [24]:
df_num_col['LotFrontage'] = df_num_col['LotFrontage'].replace(np.nan, df_num_col['LotFrontage'].median())

In [25]:
df_num_col.isnull().sum()

Id                0
MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea        8
BsmtFinSF1        0
BsmtFinSF2        0
BsmtUnfSF         0
TotalBsmtSF       0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      81
GarageCars        0
GarageArea        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
SalePrice         0
dtype: int64

In [26]:
df_num_col['MasVnrArea'] = df_num_col['MasVnrArea'].replace(np.nan, df_num_col['MasVnrArea'].median())

In [27]:
df_num_col['GarageYrBlt'] = df_num_col['GarageYrBlt'].replace(np.nan, df_num_col['GarageYrBlt'].median())

In [28]:
df_num_col.isnull().sum().sum()

np.int64(0)

In [29]:
df_obj_col

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1456,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,Attchd,Unf,TA,TA,Y,WD,Normal
1457,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1458,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
1459,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal

In [30]:
df_obj_col.isnull().sum()

MSZoning          0
Street            0
LotShape          0
LandContour       0
Utilities         0
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
ExterQual         0
ExterCond         0
Foundation        0
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Heating           0
HeatingQC         0
CentralAir        0
Electrical        1
KitchenQual       0
Functional        0
GarageType       81
GarageFinish     81
GarageQual       81
GarageCond       81
PavedDrive        0
SaleType          0
SaleCondition     0
dtype: int64

In [31]:
type(df_obj_col.isnull().sum())

pandas.Series

In [32]:
s_obj = df_obj_col.isnull().sum()

In [33]:
s_obj

MSZoning          0
Street            0
LotShape          0
LandContour       0
Utilities         0
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
ExterQual         0
ExterCond         0
Foundation        0
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Heating           0
HeatingQC         0
CentralAir        0
Electrical        1
KitchenQual       0
Functional        0
GarageType       81
GarageFinish     81
GarageQual       81
GarageCond       81
PavedDrive        0
SaleType          0
SaleCondition     0
dtype: int64

In [34]:
null_obj_list = s_obj[s_obj > 0].index.to_list()

In [35]:
null_obj_list

['BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [36]:
for i in null_obj_list:
    df_obj_col[i] = df_obj_col[i].replace(np.nan, df_obj_col[i].mode()[0])

In [37]:
df_obj_col.isnull().sum().sum()

np.int64(0)

# all data is cleaned

# encoding of categorical data

In [38]:
df_obj_col

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1456,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,Attchd,Unf,TA,TA,Y,WD,Normal
1457,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal
1458,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal
1459,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal

In [39]:
df_obj_col.isnull().sum().sum()

np.int64(0)

In [40]:
df_obj_col.shape

(1460, 37)

In [41]:
for i in df_obj_col.columns:
    print(df_obj_col[i].value_counts())
    print("----------------------------------------------------------------")

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64
----------------------------------------------------------------
Street
Pave    1454
Grvl       6
Name: count, dtype: int64
----------------------------------------------------------------
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64
----------------------------------------------------------------
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64
----------------------------------------------------------------
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64
----------------------------------------------------------------
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64
----------------------------------------------------------------
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64
----------------------------------------------------------------
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64
----------------------------------------------------------------
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64
----------------------------------------------------------------
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64
----------------------------------------------------------------
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64
----------------------------------------------------------------
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64
----------------------------------------------------------------
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64
----------------------------------------------------------------
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64
----------------------------------------------------------------
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64
----------------------------------------------------------------
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64
----------------------------------------------------------------
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64
----------------------------------------------------------------
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64
----------------------------------------------------------------
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64
----------------------------------------------------------------
BsmtQual
TA    686
Gd    618
Ex    121
Fa     35
Name: count, dtype: int64
----------------------------------------------------------------
BsmtCond
TA    1348
Gd      65
Fa      45
Po       2
Name: count, dtype: int64
----------------------------------------------------------------
BsmtExposure
No    991
Av    221
Gd    134
Mn    114
Name: count, dtype: int64
----------------------------------------------------------------
BsmtFinType1
Unf    467
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: count, dtype: int64
----------------------------------------------------------------
BsmtFinType2
Unf    1294
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: count, dtype: int64
----------------------------------------------------------------
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64
----------------------------------------------------------------
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64
----------------------------------------------------------------
CentralAir
Y    1365
N      95
Name: count, dtype: int64
----------------------------------------------------------------
Electrical
SBrkr    1335
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64
----------------------------------------------------------------
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64
----------------------------------------------------------------
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64
----------------------------------------------------------------
GarageType
Attchd     951
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64
----------------------------------------------------------------
GarageFinish
Unf    686
RFn    422
Fin    352
Name: count, dtype: int64
----------------------------------------------------------------
GarageQual
TA    1392
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64
----------------------------------------------------------------
GarageCond
TA    1407
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64
----------------------------------------------------------------
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64
----------------------------------------------------------------
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64
----------------------------------------------------------------
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64
----------------------------------------------------------------

In [42]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

# this do not help for the adding encoded data back to the df_obj_col and replace it if do so

In [43]:
encoded_MSZoning = pd.get_dummies(df['MSZoning'], prefix='MSZoning',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['MSZoning'])
df_obj_col = pd.concat([df_obj_col,encoded_MSZoning], axis= 1)

In [44]:
df_obj_col.shape

(1460, 40)

In [45]:
df_obj_col

,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
2,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
3,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml,0,0,1,0
4,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,Pave,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1456,Pave,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,Attchd,Unf,TA,TA,Y,WD,Normal,0,0,1,0
1457,Pave,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1458,Pave,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal,0,0,1,0
1459,Pave,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal,0,0,1,0

In [46]:
arr = le.fit_transform(df_obj_col['Street'])
df_obj_col['Street'] = pd.DataFrame(arr,columns=['Street'])

In [47]:
df_obj_col

,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Heating,HeatingQC,CentralAir,Electrical,KitchenQual,Functional,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,SaleType,SaleCondition,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM
0,1,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1,1,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,Gd,TA,Gd,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
2,1,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Mn,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
3,1,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,TA,Gd,No,ALQ,Unf,GasA,Gd,Y,SBrkr,Gd,Typ,Detchd,Unf,TA,TA,Y,WD,Abnorml,0,0,1,0
4,1,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,Gd,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,TA,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1456,1,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,Plywood,Plywood,TA,TA,CBlock,Gd,TA,No,ALQ,Rec,GasA,TA,Y,SBrkr,TA,Min1,Attchd,Unf,TA,TA,Y,WD,Normal,0,0,1,0
1457,1,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,Gable,CompShg,CemntBd,CmentBd,Ex,Gd,Stone,TA,Gd,No,GLQ,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Attchd,RFn,TA,TA,Y,WD,Normal,0,0,1,0
1458,1,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,Hip,CompShg,MetalSd,MetalSd,TA,TA,CBlock,TA,TA,Mn,GLQ,Rec,GasA,Gd,Y,FuseA,Gd,Typ,Attchd,Unf,TA,TA,Y,WD,Normal,0,0,1,0
1459,1,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,Gd,TA,CBlock,TA,TA,No,BLQ,LwQ,GasA,Gd,Y,SBrkr,TA,Typ,Attchd,Fin,TA,TA,Y,WD,Normal,0,0,1,0

# one hot encoding

In [48]:
encoded_LotShape = pd.get_dummies(df['LotShape'], prefix='LotShape',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['LotShape'])
df_obj_col = pd.concat([df_obj_col,encoded_LotShape], axis= 1)

In [49]:
encoded_LandContour = pd.get_dummies(df['LandContour'], prefix= 'LandContour',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['LandContour'])
df_obj_col = pd.concat([df_obj_col,encoded_LandContour], axis= 1)

# label encoding

In [50]:
arr1 = le.fit_transform(df_obj_col['Utilities'])
df_obj_col['Utilities'] = pd.DataFrame(arr1,columns=['Utilities'])

# one hot

In [51]:
encoded_LotConfig = pd.get_dummies(df['LotConfig'], prefix='LotConfig',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['LotConfig'])
df_obj_col = pd.concat([df_obj_col,encoded_LotConfig], axis= 1)

In [52]:
encoded_LandSlope = pd.get_dummies(df['LandSlope'], prefix='LandSlope',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['LandSlope'])
df_obj_col = pd.concat([df_obj_col,encoded_LandSlope], axis= 1)

# frequency encoding

In [53]:
s1 = df_obj_col['Neighborhood'].value_counts()
df_obj_col['Neighborhood'] = df_obj_col['Neighborhood'].map(s1)

# one hot encoding

In [54]:
encoded_Condition1 = pd.get_dummies(df['Condition1'], prefix='Condition1',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Condition1'])
df_obj_col = pd.concat([df_obj_col,encoded_Condition1], axis= 1)

In [55]:
encoded_Condition2 = pd.get_dummies(df['Condition2'], prefix='Condition2',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Condition2'])
df_obj_col = pd.concat([df_obj_col,encoded_Condition2], axis= 1)

In [56]:
encoded_BldgType = pd.get_dummies(df['BldgType'], prefix='BldgType',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['BldgType'])
df_obj_col = pd.concat([df_obj_col,encoded_BldgType], axis= 1)

In [57]:
encoded_HouseStyle = pd.get_dummi  es(df['HouseStyle'], prefix='HouseStyle',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['HouseStyle'])
df_obj_col = pd.concat([df_obj_col,encoded_HouseStyle], axis= 1)

In [58]:
encoded_RoofStyle = pd.get_dummies(df['RoofStyle'], prefix='RoofStyle',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['RoofStyle'])
df_obj_col = pd.concat([df_obj_col,encoded_RoofStyle], axis= 1)

In [59]:
encoded_RoofMatl = pd.get_dummies(df['RoofMatl'], prefix='RoofMatl',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['RoofMatl'])
df_obj_col = pd.concat([df_obj_col,encoded_RoofMatl], axis= 1)

# frequency

In [60]:
s2 = df_obj_col['Exterior1st'].value_counts()
df_obj_col['Exterior1st'] = df_obj_col['Exterior1st'].map(s2)

In [61]:
s3 = df_obj_col['Exterior2nd'].value_counts()
df_obj_col['Exterior2nd'] = df_obj_col['Exterior2nd'].map(s3)

# ordinal encoding

In [62]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [63]:
a1 = oe.fit_transform(df_obj_col[['ExterQual']])
df_obj_col['ExterQual'] = pd.DataFrame(a1,columns=['ExterQual'])

In [64]:
a2 = oe.fit_transform(df_obj_col[['ExterCond']])
df_obj_col['ExterCond'] = pd.DataFrame(a2,columns=['ExterCond'])

# one hot

In [65]:
encoded_Foundation = pd.get_dummies(df['Foundation'], prefix='Foundation',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Foundation'])
df_obj_col = pd.concat([df_obj_col,encoded_Foundation], axis= 1)

# ordinal

In [66]:
a3 = oe.fit_transform(df_obj_col[['BsmtQual']])
df_obj_col['BsmtQual'] = pd.DataFrame(a3,columns=['BsmtQual'])

In [67]:
a4 = oe.fit_transform(df_obj_col[['BsmtCond']])
df_obj_col['BsmtCond'] = pd.DataFrame(a4,columns=['BsmtCond'])

# one hot

In [68]:
encoded_BsmtExposure = pd.get_dummies(df['BsmtExposure'], prefix='BsmtExposure',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['BsmtExposure'])
df_obj_col = pd.concat([df_obj_col,encoded_BsmtExposure], axis= 1)

In [69]:
encoded_BsmtFinType1 = pd.get_dummies(df['BsmtFinType1'], prefix='BsmtFinType1',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['BsmtFinType1'])
df_obj_col = pd.concat([df_obj_col,encoded_BsmtFinType1], axis= 1)

In [70]:
encoded_BsmtFinType2 = pd.get_dummies(df['BsmtFinType2'], prefix='BsmtFinType2',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['BsmtFinType2'])
df_obj_col = pd.concat([df_obj_col,encoded_BsmtFinType2], axis= 1)

In [71]:
encoded_Heating = pd.get_dummies(df['Heating'], prefix='Heating',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Heating'])
df_obj_col = pd.concat([df_obj_col,encoded_Heating], axis= 1)

# ordinal

In [72]:
a5 = oe.fit_transform(df_obj_col[['HeatingQC']])
df_obj_col['HeatingQC'] = pd.DataFrame(a5,columns=['HeatingQC'])

# label

In [73]:
arr2 = le.fit_transform(df_obj_col['CentralAir'])
df_obj_col['CentralAir'] = pd.DataFrame(arr2,columns=['CentralAir'])

# one hot

In [74]:
encoded_Electrical = pd.get_dummies(df['Electrical'], prefix='Electrical',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Electrical'])
df_obj_col = pd.concat([df_obj_col,encoded_Electrical], axis= 1)

# ordinal

In [75]:
a6 = oe.fit_transform(df_obj_col[['KitchenQual']])
df_obj_col['KitchenQual'] = pd.DataFrame(a6,columns=['KitchenQual'])

# one hot

In [76]:
encoded_Functional = pd.get_dummies(df['Functional'], prefix='Functional',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['Functional'])
df_obj_col = pd.concat([df_obj_col,encoded_Functional], axis= 1)

In [77]:
encoded_GarageType = pd.get_dummies(df['GarageType'], prefix='GarageType',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['GarageType'])
df_obj_col = pd.concat([df_obj_col,encoded_GarageType], axis= 1)

In [78]:
encoded_GarageFinish = pd.get_dummies(df['GarageFinish'], prefix='GarageFinish',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['GarageFinish'])
df_obj_col = pd.concat([df_obj_col,encoded_GarageFinish], axis= 1)

# ordinal

In [79]:
a7 = oe.fit_transform(df_obj_col[['GarageQual']])
df_obj_col['GarageQual'] = pd.DataFrame(a7,columns=['GarageQual'])

In [80]:
a8 = oe.fit_transform(df_obj_col[['GarageCond']])
df_obj_col['GarageCond'] = pd.DataFrame(a6,columns=['GarageCond'])

# one hot

In [81]:
encoded_PavedDrive = pd.get_dummies(df['PavedDrive'], prefix='PavedDrive',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['PavedDrive'])
df_obj_col = pd.concat([df_obj_col,encoded_PavedDrive], axis= 1)

In [82]:
encoded_SaleType = pd.get_dummies(df['SaleType'], prefix='SaleType',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['SaleType'])
df_obj_col = pd.concat([df_obj_col,encoded_SaleType], axis= 1)

In [83]:
encoded_SaleCondition = pd.get_dummies(df['SaleCondition'], prefix='SaleCondition',dtype= int, drop_first= True)
df_obj_col = df_obj_col.drop(columns=['SaleCondition'])
df_obj_col = pd.concat([df_obj_col,encoded_SaleCondition], axis= 1)

In [84]:
df_obj_col

,Street,Utilities,Neighborhood,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,CentralAir,KitchenQual,GarageQual,GarageCond,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_P,PavedDrive_Y,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,0,150,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1,1,0,11,220,214,3.0,4.0,2.0,3.0,0.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
2,1,0,150,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
3,1,0,51,206,38,3.0,4.0,3.0,1.0,2.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4,1,0,41,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1,0,79,515,504,3.0,4.0,2.0,3.0,0.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1456,1,0,73,108,142,3.0,4.0,2.0,3.0,4.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1457,1,0,51,61,60,0.0,2.0,3.0,1.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1458,1,0,225,220,214,3.0,4.0,3.0,3.0,2.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1459,1,0,100,222,207,2.0,4.0,3.0,3.0,2.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0

# all categorical data is encoded

# concat the num and obj column

In [85]:
df_new = pd.concat([df_num_col,df_obj_col], axis= 1)

In [86]:
df_new = df_new.drop(columns=['Id'])

In [87]:
df_new

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,Street,Utilities,Neighborhood,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,CentralAir,KitchenQual,GarageQual,GarageCond,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_P,PavedDrive_Y,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.0,2,548,0,61,0,0,0,0,0,2,2008,208500,1,0,150,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.0,2,460,298,0,0,0,0,0,0,5,2007,181500,1,0,11,220,214,3.0,4.0,2.0,3.0,0.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.0,2,608,0,42,0,0,0,0,0,9,2008,223500,1,0,150,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.0,3,642,0,35,272,0,0,0,0,2,2006,140000,1,0,51,206,38,3.0,4.0,3.0,1.0,2.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.0,3,836,192,84,0,0,0,0,0,12,2008,250000,1,0,41,515,504,2.0,4.0,2.0,3.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,953,953,953,694,0,1647,0,0,2,1,3,1,7,1,1999.0,2,460,0,40,0,0,0,0,0,8,2007,175000,1,0,79,515,504,3.0,4.0,2.0,3.0,0.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,589,1542,2073,0,0,2073,1,0,2,0,3,1,7,2,1978.0,2,500,349,0,0,0,0,0,0,2,2010,210000,1,0,73,108,142,3.0,4.0,2.0,3.0,4.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,877,1152,1188,1152,0,2340,0,0,2,0,4,1,9,2,1941.0,1,252,0,60,0,0,0,0,2500,5,2010,266500,1,0,51,61,60,0.0,2.0,3.0,1.0,0.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,0,1078,1078,0,0,1078,1,0,1,0,2,1,5,0,1950.0,1,240,366,0,112,0,0,0,0,4,2010,142125,1,0,225,220,214,3.0,4.0,3.0,3.0,2.0,1,2.0,4.0,2.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,136,1256,1256,0,0,1256,1,0,1,1,3,1,6,0,1965.0,1,276,736,68,0,0,0,0,0,6,2008,147500,1,0,100,222,207,2.0,4.0,3.0,3.0,2.0,1,3.0,4.0,3.0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0

# splitting the data by train_test_split

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X = df_new.drop(columns=['SalePrice'])
y = df_new['SalePrice']

In [90]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state= 42)

In [91]:
X_train.shape

(1168, 159)

In [92]:
X_test.shape

(292, 159)

# data is splitted

# now scaling the features(X_train and X_test)

In [93]:
from sklearn.preprocessing import StandardScaler

In [94]:
ss = StandardScaler()

In [95]:
X_train_scale = pd.DataFrame(ss.fit_transform(X_train), columns=X_train.columns)

In [96]:
X_test_scale = pd.DataFrame(ss.transform(X_test), columns=X_test.columns)

In [97]:
X_train_scale

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,Street,Utilities,Neighborhood,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,CentralAir,KitchenQual,GarageQual,GarageCond,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_P,PavedDrive_Y,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-0.866764,-0.004193,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.597889,1.037269,-0.285504,-0.400282,0.572612,0.374235,-0.801923,-0.118999,-0.407093,1.105320,-0.24287,-1.055566,-0.764098,0.136218,-0.212757,-0.964566,-0.958592,-0.904403,-1.056544,-0.863837,1.188402,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,1.650065,0.058621,-0.029273,1.965335,-0.422480,-0.395280,0.660379,-2.285315,0.832883,0.290472,1.401559,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,3.198557,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,1.563786,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1,0.074110,-0.493958,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.597889,-0.971996,-0.285504,0.511920,-0.596547,-0.958202,0.955088,-0.118999,0.083170,-0.818694,-0.24287,0.773664,1.236947,0.136218,-0.212757,0.270755,0.592150,0.593542,0.295092,-0.456264,-0.740157,-0.138015,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,0.893677,0.058621,-0.029273,-0.332963,1.259648,1.288417,-0.778656,0.374623,-0.322470,0.290472,0.252369,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,-1.288640,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,-0.988085,-0.077648,-0.097506,1.498147,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,1.563786,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
2,-0.631546,-0.137765,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.597889,-0.971996,-0.285504,0.505196,-0.603357,-0.965964,-0.801923,-0.118999,-1.395250,-0.818694,-0.24287,-1.055566,-0.764098,-1.106774,-0.212757,-1.582227,-0.958592,0.052618,-2.408179,-2.257169,1.790113,-0.714352,2.290826,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,0.137290,0.058621,-0.029273,-0.002386,-0.422480,-0.493980,0.660379,0.374623,-1.477824,0.290472,0.252369,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,4.086193,-2.474258,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,-3.322836,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,-0.598448,-0.639474,-0.835269,6.761657,-3.304295,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
3,-0.161109,-0.449434,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.861522,0.267995,-0.285504,-0.915776,-0.750921,-0.487321,0.989227,-0.118999,0.458975,1.105320,-0.24287,-1.055566,1.236947,0.136218,-0.212757,0.270755,2.142892,-1.653375,-1.056544,-1.119755,-0.740157,-0.714352,3.902257,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,-0.619098,0.058621,-0.029273,-1.183018,-0.502310,-0.493980,0.660379,0.374623,-0.322470,0.290472,-0.896821,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,-1.541338,-0.213677,-0.088121,4.086193,-2.474258,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,-0.988085,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
4,-0.161109,-0.894674,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.597889,-0.496920,-0.285504,0.532091,-0.081209,-0.370895,0.711564,-0.118999,0.312087,-0.818694,-0.24287,0.773664,-0.764098,0.136218,-0.212757,-0.346905,0.592150,-2.277519,-1.056544,-0.797488,-0.740157,-0.714352,3.547742,-0.121008,-0.275838,-0.070993,-0.09274,-0.508010,1.650065,0.058621,-0.029273,-1.183018,-1.391842,-0.493980,0.660379,0.374623,0.832883,0.290472,1.401559,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,-0.988085,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,4.223590,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1163,-0.866764,0.351999,-0.127631,-0.088934,-0.524174,1.142582,1.018222,-0.597889,-0.919694,-0.285504,1.612389,0.572612,0.374235,-0.801923,-0.118999,-0.407093,-0.818694,-0.24287,0.773664,-0.764098,0.136218,-0.212757,-0.346905,0.592150,1.134467,0.295092,-0.171910,-0.740157,-0.397367,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-1.257196,-0.619098,0.058621,-0.029273,0.784703,1.259648,1.288417,-0.778656,0.374623,-0.322470,0.290472,0.252369,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,-1.288640,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,1.600305,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,1.563786,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1164,-0.161109,-0.226813,-0.268313,-1.551955,-2.316957,-1.401254,-1.683818,-0.597889,0.383495,-0.285504,-0.158223,0.136732,0.410457,0.684253,-0.118999,0.865302,1.105320,-0.24287,0.773664,-0.764098,1.379210,-0.212757,0.270755,2.142892,0.094227,0.295092,0.472624,2.584680,-0.080381,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,2.114141,0.893677,0.058621,-0.029273,-1.183018,-1.528693,-0.813301,0.660379,0.374623,0.832883,0.290472,1.401559,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,-0.988085,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,2.914779,-0.624881,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,6.267046,-0.106092,-0.029273,-3.592320,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1165,-0.866764,-0.449434,-0.234096,-0.820445,1.268609,-0.520696,0.246211,-0.597889,-0.608062,-0.285504,0.283309,-0.448983,-0.790030,-0.801923,-0.118999,-1.265531,1.105320,-0.24287,-1.055566,-0.764098,-1.106774,-0.212757,-0.964566,-0.958592,-0.904403,0.295092,0.453667,-0.740157,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.882603,-1.375486,0.058621,-0.029273,-0.002386,-1.528693,-0.813301,0.660379,0.374623,0.832883,0.290472,1.401559,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,3.198557,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,-3.304295,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1166,-0.161109,-0.672054,-0.283376,0.642577,2.165000,-1.727387,0.632217,-0.597889,-0.971996,-0.285504,0.765184,-0.340013,-0.665842,0.367900,-0.118999,-0.193438,-0.818694,-0.24287,-1.055566,1.236947,0.136218,-0.212757,0.270755,0.592150,-2.235909,-1.056544,-1.233497,-0.740157,2.743670,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,-0.619098,0.058621,-0.029273,-0.773732,-0.502310,-0.493980,-0.778656,0.374623,0.832883,0.290472,0.252369,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,-1.541338,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.285450,-0.101885,-0.988085,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636
1167,1.485421,-0.761102,-0.651399,0.642577,-0.524174,1.175195,1.066473,0.154982,-0.971996,-0.285504,1.798415,0.706555,0.997764,-0.801923,-0.118999,0.052648,-0.818694,-0.24287,0.773664,-0.764098,-1.106774,-0.212757,0.270755,0.592150,1.176076,1.646727,0.870719,0.362979,-0.426183,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,0.893677,0.058621,-0.029273,-1.308952,1.259648,1.288417,-0.778656,0.374623,-0.322470,0.290472,-0.896821,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.17576,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,3.503245,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,-0.639474,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.46002,-0.302636

In [98]:
X_test_scale

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,Street,Utilities,Neighborhood,Exterior1st,Exterior2nd,ExterQual,ExterCond,BsmtQual,BsmtCond,HeatingQC,CentralAir,KitchenQual,GarageQual,GarageCond,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,LotConfig_CulDSac,LotConfig_FR2,LotConfig_FR3,LotConfig_Inside,LandSlope_Mod,LandSlope_Sev,Condition1_Feedr,Condition1_Norm,Condition1_PosA,Condition1_PosN,Condition1_RRAe,Condition1_RRAn,Condition1_RRNe,Condition1_RRNn,Condition2_Feedr,Condition2_Norm,Condition2_PosA,Condition2_PosN,Condition2_RRAe,Condition2_RRAn,Condition2_RRNn,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,RoofMatl_CompShg,RoofMatl_Membran,RoofMatl_Metal,RoofMatl_Roll,RoofMatl_Tar&Grv,RoofMatl_WdShake,RoofMatl_WdShngl,Foundation_CBlock,Foundation_PConc,Foundation_Slab,Foundation_Stone,Foundation_Wood,BsmtExposure_Gd,BsmtExposure_Mn,BsmtExposure_No,BsmtFinType1_BLQ,BsmtFinType1_GLQ,BsmtFinType1_LwQ,BsmtFinType1_Rec,BsmtFinType1_Unf,BsmtFinType2_BLQ,BsmtFinType2_GLQ,BsmtFinType2_LwQ,BsmtFinType2_Rec,BsmtFinType2_Unf,Heating_GasA,Heating_GasW,Heating_Grav,Heating_OthW,Heating_Wall,Electrical_FuseF,Electrical_FuseP,Electrical_Mix,Electrical_SBrkr,Functional_Maj2,Functional_Min1,Functional_Min2,Functional_Mod,Functional_Sev,Functional_Typ,GarageType_Attchd,GarageType_Basment,GarageType_BuiltIn,GarageType_CarPort,GarageType_Detchd,GarageFinish_RFn,GarageFinish_Unf,PavedDrive_P,PavedDrive_Y,SaleType_CWD,SaleType_Con,SaleType_ConLD,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-0.866764,-0.004193,-0.211594,-0.088934,2.165000,-0.259789,0.873470,-0.597889,0.472844,-0.285504,-0.391317,-0.006292,-0.262230,-0.801923,-0.118999,-0.876372,-0.818694,3.991043,-1.055566,-0.764098,0.136218,-0.212757,-0.346905,-0.958592,-0.654745,-1.056544,-1.006014,0.740976,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-1.631789,-1.375486,0.058621,-0.029273,-0.411671,-0.411076,-0.435921,0.660379,0.374623,0.832883,0.290472,1.401559,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,1.600305,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,1.563786,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
1,0.074110,1.242480,0.145643,1.374088,-0.524174,0.751222,0.487465,1.498567,1.276986,-0.285504,-0.312872,0.910874,0.855465,1.751660,-0.118999,2.088099,1.105320,-0.242870,0.773664,1.236947,0.136218,-0.212757,1.506077,2.142892,0.635152,0.295092,1.117159,0.694691,-0.253282,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.882603,1.650065,0.058621,-0.029273,-0.931150,-0.411076,-0.435921,-0.778656,0.374623,-2.633177,0.290472,-0.896821,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,-1.288640,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,-1.541338,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,-0.988085,-0.077648,-0.097506,1.498147,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,-1.388279,-0.343079,1.600305,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,1.563786,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
2,-0.631546,-0.627530,-0.160826,-0.820445,0.372217,-1.433867,-1.683818,-0.597889,-0.971996,-0.285504,0.980347,-0.122072,-0.365720,-0.801923,-0.118999,-0.952678,-0.818694,-0.242870,-1.055566,-0.764098,-1.106774,-0.212757,-0.964566,0.592150,-2.152690,0.295092,-0.551048,-0.740157,-0.714352,1.742939,-0.121008,-0.275838,-0.070993,-0.09274,-1.257196,1.650065,0.058621,-0.029273,0.202257,-1.528693,-1.417110,0.660379,0.374623,0.832883,0.290472,0.252369,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,-1.945992,2.406387,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,-2.474258,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,-3.322836,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
3,-0.161109,-0.894674,-0.529035,-0.088934,1.268609,-0.781602,-1.683818,-0.597889,-0.102477,-0.285504,0.077111,-0.131153,-0.427814,0.700185,-0.118999,0.260581,-0.818694,-0.242870,0.773664,-0.764098,0.136218,-0.212757,0.270755,2.142892,-1.195670,0.295092,-0.266695,-0.740157,-0.368550,0.228194,-0.121008,-0.275838,-0.070993,-0.09274,1.364955,-1.375486,0.058621,-0.029273,-0.663540,-1.329118,-1.289381,0.660379,-2.285315,0.832883,0.290472,-0.896821,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,-1.945992,2.406387,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,-1.541338,-0.213677,-0.088121,4.086193,-2.474258,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,-0.988085,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
4,-0.866764,0.841764,0.205338,2.105599,-0.524174,1.175195,1.114724,-0.192497,1.255193,-0.285504,0.061422,1.267297,1.165936,-0.801923,-0.118999,0.176644,1.105320,-0.242870,0.773664,-0.764098,-1.106774,-0.212757,-0.346905,0.592150,1.217686,1.646727,2.065003,1.018689,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,0.990362,0.893677,0.058621,-0.029273,-0.978375,1.259648,1.288417,-0.778656,0.374623,-2.633177,0.290472,-0.896821,0.276582,-2.851481,0.214591,-2.851481,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,-1.288640,5.689589,-0.150888,-3.116985,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,3.215557,-0.294129,-1.388279,-0.343079,1.600305,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,-0.639474,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,-0.631546,-0.894674,-0.443026,-1.551955,1.268609,-1.107734,0.728718,1.921333,-0.605882,-0.285504,0.377443,-0.351364,-0.099233,-0.801923,-0.118999,-0.756191,-0.818694,-0.242870,-1.055566,-0.764098,-1.106774,-0.212757,0.270755,-0.958592,0.676761,0.295092,0.927590,-0.740157,0.323055,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-1.257196,-0.619098,0.058621,-0.029273,0.202257,-1.534395,-1.486780,0.660379,0.374623,-1.477824,0.290472,1.401559,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,-1.945992,2.406387,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,-3.116985,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,3.198557,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,12.878554,-0.125109,-2.173819,-0.302636
288,-0.866764,2.400105,0.508459,0.642577,-0.524174,1.109968,0.969972,-0.505228,1.804363,-0.285504,-0.705096,1.062978,0.933083,-0.801923,-0.118999,0.004957,1.105320,-0.242870,0.773664,-0.764098,0.136218,-0.212757,0.270755,0.592150,1.092857,0.295092,-0.219303,0.555835,-0.195649,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,-0.133417,0.893677,0.058621,-0.029273,-1.183018,1.259648,1.288417,-0.778656,0.374623,-2.633177,0.290472,-0.896821,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,-1.288640,-0.175760,6.627449,-3.116985,-0.278372,-0.18338,-0.050746,0.648787,4.679953,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,-1.859574,-0.088121,1.992539,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,-1.388279,-0.343079,-0.624881,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,-0.639474,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
289,0.074110,-0.315862,-0.231585,0.642577,-0.524174,1.109968,0.969972,-0.597889,0.440155,-0.285504,-1.099561,-0.757732,-1.141897,0.854947,-0.118999,-0.136208,1.105320,-0.242870,0.773664,1.236947,0.136218,-0.212757,0.270755,0.592150,1.092857,0.295092,-0.314087,-0.462445,-0.455000,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,1.364955,0.137290,0.058621,-0.029273,0.784703,-1.528693,-1.417110,-0.778656,0.374623,-0.322470,0.290472,-0.896821,0.276582,-0.419550,0.214591,-0.419550,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,-0.988085,-0.077648,-0.097506,1.498147,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,-0.871227,1.116313,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,-1.388279,-0.343079,1.600305,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,0.827904,-0.117851,-0.26008,-0.077648,-0.598448,-0.639474,-0.835269,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
290,0.309329,-0.449434,-0.149296,-1.551955,-0.524174,-1.009895,-1.683818,-0.597889,-0.971996,-0.285504,0.413303,-0.696436,-1.072042,0.916397,-0.118999,-0.033196,1.105320,-0.242870,-1.055566,-0.764098,1.379210,-0.212757,0.270755,0.592150,-1.611766,-1.056544,-0.854359,0.185551,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,1.364955,0.893677,0.058621,-0.029273,-0.002386,-0.422480,-0.395280,0.660379,0.374623,0.832883,0.290472,1.401559,0.276582,0.796416,-4.865997,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,-2.474258,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,-0.988085,-0.077648,-0.097506,1.498147,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,3.399873,-1.388279,-0.343079,-0.624881,-0.236765,-0.312641,1.544509,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,6.761657,-3.304295,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636
291,-0.866764,-0.004193,-0.238931,-1.551955,1.268609,-0.031496,-0.718804,-0.597889,-0.555760,-0.285504,0.229518,-0.448983,-0.790030,-0.801923,-0.118999,-1.265531,-0.818694,-0.242870,-1.055566,-0.764098,0.136218,-0.212757,-0.964566,-0.958592,0.635152,0.295092,-0.062908,-0.740157,-0.714352,-0.351921,-0.121008,-0.275838,-0.070993,-0.09274,0.241176,0.893677,0.058621,-0.029273,1.965335,-0.422480,-0.395280,0.660379,-2.285315,0.832883,0.290472,-0.896821,0.276582,0.796416,0.214591,0.796416,-0.218022,-0.114059,0.513877,-0.415561,-0.180871,-0.083045,0.776012,-0.175760,-0.150888,0.320823,-0.278372,-0.18338,-0.050746,0.648787,-0.213677,-0.088121,-0.244727,0.404162,-0.083045,-0.114059,-0.092928,-0.128593,-0.029273,-0.065568,-0.050746,0.097506,-0.029273,-0.041416,-0.029273,-0.029273,-0.029273,-0.159565,-0.190735,-0.167836,-0.28545,-0.101885,1.012059,-0.077648,-0.097506,-0.667491,-0.156721,-0.215859,0.537758,-0.088121,-0.501872,-0.065568,-0.041416,0.128593,0.0,-0.029273,-0.029273,-0.088121,-0.050746,-0.058621,1.147807,-0.895806,-0.131991,-0.065568,-0.050746,-0.310988,-0.294129,0.720316,-0.343079,-0.624881,-0.236765,-0.312641,-0.647455,-0.138554,-0.092928,-0.178331,-0.20248,0.396966,0.156721,-0.114059,-0.071858,-0.041416,-0.058621,-0.144841,-0.050746,0.0,0.300948,-0.058621,-0.156721,-0.159565,-0.106092,-0.029273,0.278372,-1.207869,-0.117851,-0.26008,-0.077648,1.670990,-0.639474,1.197219,-0.147893,0.302636,-0.058621,-0.041416,-0.077648,-0.058621,-0.058621,-0.300948,-0.041416,0.39262,-0.058621,-0.077648,-0.125109,0.460020,-0.302636

In [99]:
X_test_scale.shape

(292, 159)

In [100]:
from sklearn.linear_model import LinearRegression

In [102]:
lr=LinearRegression()

In [103]:
lr.fit(X_train_scale,y_train)

LinearRegression()

In [105]:
y_pred = lr.predict(X_test_scale)

In [106]:
y_pred

array([ 145648.31841992,  342323.36301526,  101636.21519676,
        159743.58014917,  334632.08654977,   61846.57821739,
        228932.85074598,  138233.03778705,   58126.34930833,
        150018.11358102,  143709.93264848,  105101.95955094,
         61629.93086854,  203176.23885761,  160832.27318379,
        132275.62724715,  195895.65216751,  123445.44357385,
        116097.60208754,  224746.9215482 ,  138493.32023544,
        201350.43349925,  167621.74353534,  118782.74227831,
        206828.94834822,  160907.87148542,  205092.79217541,
         96432.93177299,  164598.55765825,  203303.79386484,
        123189.9350949 ,  264086.64616458,  248671.3367997 ,
        104316.93054955,  238344.68604035,  146721.12493413,
        137109.10720963,  206311.03815687,  296181.65505121,
         94186.5407799 ,  113329.91714446,  236260.59951796,
         98370.73922834,  355823.36170517,  134740.14607628,
        157038.3858985 ,   91339.58142972,  133142.89012677,
        389218.91428274,  128996.03893335,  115445.2135117 ,
        246654.27806917,  107587.56611296,  301332.8802411 ,
        168785.22711921,  254808.60827996,  208128.32878948,
        162771.56021772,  138767.0099512 ,   81389.95881605,
         69903.34997418,  154742.38132087,  298981.16881544,
        269101.30641663,  306166.43851402,  208037.97217983,
        105422.75293046,  306028.06247613,  139908.21612765,
        179861.06322456,  116789.43468901,  106057.39503207,
        100274.617032  ,   43688.10444182,  466201.37938319,
        212359.02676178,  300675.84237814,  331143.81137379,
        113590.83146063,  117914.25634106,  122427.37750536,
         74686.04578256,  128896.64135065,   84366.01582944,
        155139.92744618,  140382.71274235,  267629.81246451,
        221883.28234445,  139303.52605312,  198526.11559831,
        150549.29738788,  140783.51051226,  137610.37616276,
        303224.40004561,  125463.01487411,  183454.7463168 ,
        196507.24741178,  179696.32038534,  222455.04921409,
        283985.76094927,  190352.07749259,  212949.81830641,
        325957.8756265 ,  144009.93812099,  201741.57465152,
        161095.33882814,  146300.49958275,  265279.35635893,
        153299.07556538,  197437.82018695,   38234.85267088,
        144670.29412855,  141161.21377288,  127379.24542143,
        209805.02402739,  115857.52535674,   93044.74174306,
         89553.72373643,  102899.22072518,  315273.32766988,
        101276.24536242,  147802.8970852 ,  176855.02640412,
        187063.32641548,  206809.2670886 ,  122285.45459373,
        244827.15131479,   72104.19342013,  142898.09695514,
        184164.69728528,  188097.02924537,  359345.58297162,
        193110.3109311 ,  138759.8018081 ,   15316.53356542,
        353161.87423839,  380487.72686436,  126496.72378089,
        244772.96124128,  592012.82499068,  344204.76683678,
        123413.92919964,  190336.99267505,  157804.88117347,
        143994.20601332,   94777.0105544 ,  233708.9466867 ,
        202010.50126976,  124214.14197995,   46934.76763873,
        131216.25046492,  127943.43409211,  255700.20434043,
        167976.77449516,   65747.40783545,  108370.73258552,
        151672.15334861,  148472.01015955,   75499.63343477,
        119591.07547719,  204970.35884744,  129554.39993464,
        323180.91345137,  169245.21804786,  111106.10736881,
        101434.04103264,  277123.331642  ,  345845.26135022,
        387600.23500085,  225151.29578542,  341238.21646419,
        105497.30344376,   96520.48679169,  131092.81220473,
        316916.78859082,  111449.32853673,  122732.83442393,
        229942.54748843,  134403.93364992,  177647.76325814,
        165631.37098239,  113487.33848893,  118486.91190475,
        152167.4909941 ,  253088.5330454 ,  132495.23611035,
        281590.17146149,  241729.31416915,  196657.2738491 ,
         72236.08764774,  115646.19970994,   79619.48845691,
        148585.44619796,  179302.84808175,  192561.19221932,
        195299.39948857,  210925.57249075,   58921.93021014,
        212271.05455914,  114926.60181102,  276568.0452318 ,
        209749.79338538,  127216.5992737 ,  308564.46873472,
        193177.40042376,  106978.36517632,  240431.49277133,
        127990.08338436,  143757.60349547,   91544.04076669,
        239915.29005478,  140175.82110415,  115983.12084928,
        171223.99675854, -552496.58069012,  253714.92084507,
        222544.69859655,  139358.37389821,  122041.17396677,
        117233.32404425,  127364.48053894,  212678.18741196,
        212135.48353805,   78501.4683225 ,  225764.73098343,
        147426.90166798,   66073.7561343 ,   73152.29213077,
        177027.49302298,  104141.69776977,   91481.494522  ,
        172600.41508321,  118773.36068542,  139605.16167081,
        242292.01666542,  140553.63821775,  212834.07570996,
        165899.39703076,  253618.28343602,  110642.65433213,
        105681.28414937,  272749.77023085,  220629.10553753,
        448925.87963115,  201421.72174352,  160427.62408759,
        142990.93882063,  174542.71236623,  145679.38718015,
         89879.41253269,  177916.19562925,  171524.82322364,
        139704.45988885,  116861.56563813,  145300.89082673,
        130206.9981012 ,  104621.48422698,  113241.52359412,
        174974.58099593,  263513.42377397,  299414.66588295,
        180401.52812167,  124140.87379775,  253646.74786583,
        340035.61606845,  219480.01217042,  177673.50168841,
        146588.6568964 ,  125645.89284676,  165269.42543068,
        397478.18015796,  212540.80444921,  234052.69026216,
         73471.6654909 ,   76975.32201211,  145094.63937848,
        154167.52214907,  314380.05978793,  224712.73116413,
        120948.9228885 ,  208101.7215849 ,  105133.7437967 ,
        201593.15523237,  115388.14578407,  302578.8569769 ,
        173365.04172883,  216923.00425518,  167015.83543648,
        248967.67379874,  195708.62091786,   94365.8845097 ,
        102448.36353032])

In [107]:
lr.score(X_test_scale,y_test)

0.6078781168992647

In [108]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [109]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [110]:
print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)

MAE : 21772.49406567563
MSE : 3007702756.359136
RMSE: 54842.52689618829